In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler

from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report,f1_score

In [ ]:
df = pd.read_csv("Hair Fall Responses - Hair Fall Responses.csv")
df.head()

Age  Gender Educational_Institution Where are you from?  \
0  18-24    Male              University               Dhaka   
1  18-24    Male              University          Chittagong   
2  18-24    Male              University              Khulna   
3  25-34  Female                   Other          Chittagong   
4  18-24    Male              University               Dhaka   

  How_long_have_you_been_suffering_from_hair_loss?  \
0                                    1 to 6 months   
1                                    1 to 6 months   
2                           I have no hair problem   
3                                    1 to 6 months   
4                                  Never hair fall   

  Does anyone in your family have such a problem?  \
0                                             Yes   
1                                             Yes   
2                                              No   
3                                             Yes   
4                                              No   

  Do you have dandruff in your hair? Do you have any type of allergy problem?  \
0                                Yes                                      Yes   
1                                 No                                      Yes   
2                                 No                                      Yes   
3                                Yes                                      Yes   
4                                 No                                       No   

  Do you suffer any kind of stress? What is your skin type? Your blood group?  \
0                               Yes                  Normal                B+   
1                               Yes             Combination                O+   
2                               Yes             Combination                O+   
3                               Yes                    Oily                B+   
4                               Yes                    Oily                A+   

  Have you taken any medicine to stop hair loss?  \
0                                             No   
1                                             No   
2                                             No   
3                                             No   
4                                             No   

  Do you take care of your hair regularly?  \
0                                       No   
1                                       No   
2                                       No   
3                                       No   
4                                      Yes   

  If yes? What do you use for hair care?  \
0                                    NaN   
1                                Shampoo   
2                                    NaN   
3                                shampoo   
4                             hair brass   

  Any other reason for your hair fall (Covid, Water, Antibiotic  \
0                                              Water              
1                                              Water              
2                                                NaN              
3                                              Water              
4                                                NaN              

  Excess_hair_fall  
0              Yes  
1               No  
2               No  
3              Yes  
4              Yes

In [ ]:
for colname in df.select_dtypes("object"):
    df[colname], _ = df[colname].factorize()

discrete_features = df.dtypes == str

In [ ]:
df.shape

(300, 16)

In [ ]:
df.columns

Index(['Age', 'Gender', 'Educational_Institution', 'Where are you from?',
       'How_long_have_you_been_suffering_from_hair_loss?',
       'Does anyone in your family have such a problem?',
       'Do you have dandruff in your hair?',
       'Do you have any type of allergy problem?',
       'Do you suffer any kind of stress?', 'What is your skin type?',
       'Your blood group?', 'Have you taken any medicine to stop hair loss?',
       'Do you take care of your hair regularly?',
       'If yes? What do you use for hair care?',
       'Any other reason for your hair fall (Covid, Water, Antibiotic',
       'Excess_hair_fall'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Age                                                            300 non-null    int64
 1   Gender                                                         300 non-null    int64
 2   Educational_Institution                                        300 non-null    int64
 3   Where are you from?                                            300 non-null    int64
 4   How_long_have_you_been_suffering_from_hair_loss?               300 non-null    int64
 5   Does anyone in your family have such a problem?                300 non-null    int64
 6   Do you have dandruff in your hair?                             300 non-null    int64
 7   Do you have any type of allergy problem?                       300 non-null    i

In [ ]:
df.describe()

Age  Gender  Educational_Institution  Where are you from?  \
count 300.00  300.00                   300.00               300.00   
mean    0.35    0.51                     0.34                 2.06   
std     0.55    0.50                     0.55                 2.49   
min     0.00    0.00                     0.00                 0.00   
25%     0.00    0.00                     0.00                 0.00   
50%     0.00    1.00                     0.00                 1.00   
75%     1.00    1.00                     1.00                 4.00   
max     4.00    1.00                     3.00                 7.00   

       How_long_have_you_been_suffering_from_hair_loss?  \
count                                            300.00   
mean                                               4.85   
std                                                6.68   
min                                                0.00   
25%                                                2.00   
50%                                                3.00   
75%                                                4.00   
max                                               34.00   

       Does anyone in your family have such a problem?  \
count                                           300.00   
mean                                              0.45   
std                                               0.50   
min                                               0.00   
25%                                               0.00   
50%                                               0.00   
75%                                               1.00   
max                                               1.00   

       Do you have dandruff in your hair?  \
count                              300.00   
mean                                 0.50   
std                                  0.50   
min                                  0.00   
25%                                  0.00   
50%                                  0.00   
75%                                  1.00   
max                                  1.00   

       Do you have any type of allergy problem?  \
count                                    300.00   
mean                                       0.49   
std                                        0.50   
min                                        0.00   
25%                                        0.00   
50%                                        0.00   
75%                                        1.00   
max                                        1.00   

       Do you suffer any kind of stress?  What is your skin type?  \
count                             300.00                   300.00   
mean                                0.45                     1.38   
std                                 0.50                     0.94   
min                                 0.00                     0.00   
25%                                 0.00                     1.00   
50%                                 0.00                     1.00   
75%                                 1.00                     2.00   
max                                 1.00                     3.00   

       Your blood group?  Have you taken any medicine to stop hair loss?  \
count             300.00                                          300.00   
mean                1.37                                            0.20   
std                 1.40                                            0.40   
min                 0.00                                            0.00   
25%                 0.00                                            0.00   
50%                 1.00                                            0.00   
75%                 2.00                                            0.00   
max                 8.00                                            1.00   

       Do you take care of your hair regularly?  \
count                                    300.00   
mean                                       0.42 

In [ ]:
df.describe().T

count  mean   std   min  \
Age                                                300.00  0.35  0.55  0.00   
Gender                                             300.00  0.51  0.50  0.00   
Educational_Institution                            300.00  0.34  0.55  0.00   
Where are you from?                                300.00  2.06  2.49  0.00   
How_long_have_you_been_suffering_from_hair_loss?   300.00  4.85  6.68  0.00   
Does anyone in your family have such a problem?    300.00  0.45  0.50  0.00   
Do you have dandruff in your hair?                 300.00  0.50  0.50  0.00   
Do you have any type of allergy problem?           300.00  0.49  0.50  0.00   
Do you suffer any kind of stress?                  300.00  0.45  0.50  0.00   
What is your skin type?                            300.00  1.38  0.94  0.00   
Your blood group?                                  300.00  1.37  1.40  0.00   
Have you taken any medicine to stop hair loss?     300.00  0.20  0.40  0.00   
Do you take care of your hair regularly?           300.00  0.42  0.49  0.00   
If yes? What do you use for hair care?             300.00 11.37 20.41 -1.00   
Any other reason for your hair fall (Covid, Wat... 300.00  3.93  9.88 -1.00   
Excess_hair_fall                                   300.00  0.40  0.49  0.00   

                                                     25%   50%   75%   max  
Age                                                 0.00  0.00  1.00  4.00  
Gender                                              0.00  1.00  1.00  1.00  
Educational_Institution                             0.00  0.00  1.00  3.00  
Where are you from?                                 0.00  1.00  4.00  7.00  
How_long_have_you_been_suffering_from_hair_loss?    2.00  3.00  4.00 34.00  
Does anyone in your family have such a problem?     0.00  0.00  1.00  1.00  
Do you have dandruff in your hair?                  0.00  0.00  1.00  1.00  
Do you have any type of allergy problem?            0.00  0.00  1.00  1.00  
Do you suffer any kind of stress?                   0.00  0.00  1.00  1.00  
What is your skin type?                             1.00  1.00  2.00  3.00  
Your blood group?                                   0.00  1.00  2.00  8.00  
Have you taken any medicine to stop hair loss?      0.00  0.00  0.00  1.00  
Do you take care of your hair regularly?            0.00  0.00  1.00  1.00  
If yes? What do you use for hair care?             -1.00  0.00 16.25 75.00  
Any other reason for your hair fall (Covid, Wat... -1.00 -1.00  2.00 42.00  
Excess_hair_fall                                    0.00  0.00  1.00  1.00

In [ ]:
df.isnull()

Age  Gender  Educational_Institution  Where are you from?  \
0    False   False                    False                False   
1    False   False                    False                False   
2    False   False                    False                False   
3    False   False                    False                False   
4    False   False                    False                False   
..     ...     ...                      ...                  ...   
295  False   False                    False                False   
296  False   False                    False                False   
297  False   False                    False                False   
298  False   False                    False                False   
299  False   False                    False                False   

     How_long_have_you_been_suffering_from_hair_loss?  \
0                                               False   
1                                               False   
2                                               False   
3                                               False   
4                                               False   
..                                                ...   
295                                             False   
296                                             False   
297                                             False   
298                                             False   
299                                             False   

     Does anyone in your family have such a problem?  \
0                                              False   
1                                              False   
2                                              False   
3                                              False   
4                                              False   
..                                               ...   
295                                            False   
296                                            False   
297                                            False   
298                                            False   
299                                            False   

     Do you have dandruff in your hair?  \
0                                 False   
1                                 False   
2                                 False   
3                                 False   
4                                 False   
..                                  ...   
295                               False   
296                               False   
297                               False   
298                               False   
299                               False   

     Do you have any type of allergy problem?  \
0                                       False   
1                                       False   
2                                       False   
3                                       False   
4                                       False   
..                                        ...   
295                                     False   
296                                     False   
297                                     False   
298                                     False   
299                                     False   

     Do you suffer any kind of stress?  What is your skin type?  \
0                                False                    False   
1                                False                    False   
2                                False                    False   
3                                False                    False   
4                                False                    False   
..                                 ...                      ...   
295                              False                    False   
296                              False                    False   
297                              False                    False   
298                              False                  

In [ ]:
df.isnull().sum()

Age                                                              0
Gender                                                           0
Educational_Institution                                          0
Where are you from?                                              0
How_long_have_you_been_suffering_from_hair_loss?                 0
Does anyone in your family have such a problem?                  0
Do you have dandruff in your hair?                               0
Do you have any type of allergy problem?                         0
Do you suffer any kind of stress?                                0
What is your skin type?                                          0
Your blood group?                                                0
Have you taken any medicine to stop hair loss?                   0
Do you take care of your hair regularly?                         0
If yes? What do you use for hair care?                           0
Any other reason for your hair fall (Covid, Water, Antibiotic 

In [ ]:
pd.set_option('Display.float','{:.2f}'.format)
df.describe()

Age  Gender  Educational_Institution  Where are you from?  \
count 300.00  300.00                   300.00               300.00   
mean    0.35    0.51                     0.34                 2.06   
std     0.55    0.50                     0.55                 2.49   
min     0.00    0.00                     0.00                 0.00   
25%     0.00    0.00                     0.00                 0.00   
50%     0.00    1.00                     0.00                 1.00   
75%     1.00    1.00                     1.00                 4.00   
max     4.00    1.00                     3.00                 7.00   

       How_long_have_you_been_suffering_from_hair_loss?  \
count                                            300.00   
mean                                               4.85   
std                                                6.68   
min                                                0.00   
25%                                                2.00   
50%                                                3.00   
75%                                                4.00   
max                                               34.00   

       Does anyone in your family have such a problem?  \
count                                           300.00   
mean                                              0.45   
std                                               0.50   
min                                               0.00   
25%                                               0.00   
50%                                               0.00   
75%                                               1.00   
max                                               1.00   

       Do you have dandruff in your hair?  \
count                              300.00   
mean                                 0.50   
std                                  0.50   
min                                  0.00   
25%                                  0.00   
50%                                  0.00   
75%                                  1.00   
max                                  1.00   

       Do you have any type of allergy problem?  \
count                                    300.00   
mean                                       0.49   
std                                        0.50   
min                                        0.00   
25%                                        0.00   
50%                                        0.00   
75%                                        1.00   
max                                        1.00   

       Do you suffer any kind of stress?  What is your skin type?  \
count                             300.00                   300.00   
mean                                0.45                     1.38   
std                                 0.50                     0.94   
min                                 0.00                     0.00   
25%                                 0.00                     1.00   
50%                                 0.00                     1.00   
75%                                 1.00                     2.00   
max                                 1.00                     3.00   

       Your blood group?  Have you taken any medicine to stop hair loss?  \
count             300.00                                          300.00   
mean                1.37                                            0.20   
std                 1.40                                            0.40   
min                 0.00                                            0.00   
25%                 0.00                                            0.00   
50%                 1.00                                            0.00   
75%                 2.00                                            0.00   
max                 8.00                                            1.00   

       Do you take care of your hair regularly?  \
count                                    300.00   
mean                                       0.42 

In [ ]:
df.Excess_hair_fall.value_counts()

0    181
1    119
Name: Excess_hair_fall, dtype: int64

In [ ]:
df.tail()

Age  Gender  Educational_Institution  Where are you from?  \
295    0       0                        0                    0   
296    0       0                        0                    0   
297    1       0                        0                    0   
298    2       1                        3                    1   
299    0       1                        1                    0   

     How_long_have_you_been_suffering_from_hair_loss?  \
295                                                28   
296                                                 4   
297                                                 3   
298                                                 3   
299                                                 0   

     Does anyone in your family have such a problem?  \
295                                                1   
296                                                1   
297                                                0   
298                                                0   
299                                                1   

     Do you have dandruff in your hair?  \
295                                   1   
296                                   0   
297                                   0   
298                                   0   
299                                   0   

     Do you have any type of allergy problem?  \
295                                         0   
296                                         1   
297                                         1   
298                                         0   
299                                         0   

     Do you suffer any kind of stress?  What is your skin type?  \
295                                  1                        2   
296                                  0                        2   
297                                  1                        2   
298                                  0                        1   
299                                  0                        1   

     Your blood group?  Have you taken any medicine to stop hair loss?  \
295                  0                                               0   
296                  3                                               0   
297                  2                                               0   
298                  1                                               0   
299                  1                                               0   

     Do you take care of your hair regularly?  \
295                                         1   
296                                         0   
297                                         0   
298                                         0   
299                                         0   

     If yes? What do you use for hair care?  \
295                                       7   
296                                      -1   
297                                      -1   
298                                      75   
299                                      -1   

     Any other reason for your hair fall (Covid, Water, Antibiotic  \
295                                                 -1               
296                                                  0               
297                                                 -1               
298                                                 -1               
299                                                 -1               

     Excess_hair_fall  
295                 0  
296                 0  
297                 1  
298                 0  
299                 1

In [ ]:
print(df.columns)
print(df.columns)

Index(['Age', 'Gender', 'Educational_Institution', 'Where are you from?',
       'How_long_have_you_been_suffering_from_hair_loss?',
       'Does anyone in your family have such a problem?',
       'Do you have dandruff in your hair?',
       'Do you have any type of allergy problem?',
       'Do you suffer any kind of stress?', 'What is your skin type?',
       'Your blood group?', 'Have you taken any medicine to stop hair loss?',
       'Do you take care of your hair regularly?',
       'If yes? What do you use for hair care?',
       'Any other reason for your hair fall (Covid, Water, Antibiotic',
       'Excess_hair_fall'],
      dtype='object')
Index(['Age', 'Gender', 'Educational_Institution', 'Where are you from?',
       'How_long_have_you_been_suffering_from_hair_loss?',
       'Does anyone in your family have such a problem?',
       'Do you have dandruff in your hair?',
       'Do you have any type of allergy problem?',
       'Do you suffer any kind of stress?', 'What is yo

In [ ]:
X = df.drop('Excess_hair_fall', axis=1)
y = df['Excess_hair_fall']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
kfold = model_selection.KFold(n_splits = 3)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        pred = clf.predict(X_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

    elif train==False:
        pred = clf.predict(X_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

In [ ]:
from sklearn.svm import SVC

svm_clf = SVC(kernel='rbf', gamma=0.1, C=1.0)
svm_clf.fit(X_train, y_train)

print_score(svm_clf, X_train, y_train, X_test, y_test, train=True)
print_score(svm_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:
Accuracy Score: 91.25%
Confusion Matrix: 
 [[144   2]
 [ 19  75]]

Test Result:
Accuracy Score: 75.00%
Confusion Matrix: 
 [[35  0]
 [15 10]]



In [ ]:
from sklearn.tree import DecisionTreeClassifier


tree_clf = DecisionTreeClassifier(random_state=42)
tree_clf.fit(X_train, y_train)

print_score(tree_clf, X_train, y_train, X_test, y_test, train=True)
print_score(tree_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:
Accuracy Score: 99.17%
Confusion Matrix: 
 [[146   0]
 [  2  92]]

Test Result:
Accuracy Score: 73.33%
Confusion Matrix: 
 [[28  7]
 [ 9 16]]



In [ ]:
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression(solver='liblinear')
lr_clf.fit(X_train, y_train)

print_score(lr_clf, X_train, y_train, X_test, y_test, train=True)
print_score(lr_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:
Accuracy Score: 82.08%
Confusion Matrix: 
 [[125  21]
 [ 22  72]]

Test Result:
Accuracy Score: 75.00%
Confusion Matrix: 
 [[29  6]
 [ 9 16]]



In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

rf_clf = RandomForestClassifier(n_estimators=1000, random_state=42)
rf_clf.fit(X_train, y_train)

print_score(rf_clf, X_train, y_train, X_test, y_test, train=True)
print_score(rf_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:
Accuracy Score: 99.17%
Confusion Matrix: 
 [[146   0]
 [  2  92]]

Test Result:
Accuracy Score: 83.33%
Confusion Matrix: 
 [[34  1]
 [ 9 16]]



In [ ]:
from xgboost import XGBClassifier

xgb_clf = XGBClassifier(use_label_encoder=False)
xgb_clf.fit(X_train, y_train)

print_score(xgb_clf, X_train, y_train, X_test, y_test, train=True)
print_score(xgb_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:
Accuracy Score: 94.58%
Confusion Matrix: 
 [[144   2]
 [ 11  83]]

Test Result:
Accuracy Score: 85.00%
Confusion Matrix: 
 [[34  1]
 [ 8 17]]



In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
knn_scores=[]
for k in range(1,20):
    knn=KNeighborsClassifier(n_neighbors=k)
    scores=cross_val_score(knn,X_train,y_train,cv=5)
    knn_scores.append(scores.mean())

x_ticks = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
x_labels = x_ticks